### ISSUE TITLE
content-type always octet-stream, 

### ISSUE THREAD

**Issue by doomzhou** [Vim-cn/elimage#7]
hi when i upload images always download ,cannot display in chrome , ff , ie...
how can i fix it. error below 

    [root@iZ281371ci1Z site-enable]#curl -I http://127.0.0.1:8888/75/dab8172ce50a54d81516d4cc982d6776edad67.jpg
    HTTP/1.1 200 OK
    Last-Modified: Sat, 05 Dec 2015 06:14:54 GMT
    Content-Length: 40358
    Server: TornadoServer/4.3
    Content-Type: application/octet-stream
    Date: Sat, 05 Dec 2015 07:27:29 GMT
    Etag: "cce8da2d1bcb2f19fda0fcd4171ff434"
    Accept-Ranges: bytes

**Comment by lilydjwg** [comment]
What does the following command report for your file?

```
file -i dab8172ce50a54d81516d4cc982d6776edad67.jpg
```

**Comment by doomzhou** [comment]
thanks for immediate reply :)

    @barch ➜  Downloads  file -i th.jpg
    th.jpg: image/jpeg; charset=binary
    @barch ➜  Downloads

**Comment by lilydjwg** [comment]
It's strange. Can you do a strace and attach the log?

```
strace -o the.log -s 128 -f -p $pid_of_elimage
```

Then do then curl command to reproduce the problem. Ctrl-C and give me `the.log` file.

**Comment by doomzhou** [comment]
ok.  access and upload log both in zip package. 
and same image, return url(after upload) was same.

really thanks. buddy

[access_and_upload.log.zip](https://github.com/Vim-cn/elimage/files/52815/access_and_upload.log.zip)

**Comment by lilydjwg** [comment]
You've straced the wrong process.... Please disable autoreload, and retry.
